'''
CISC 471 HW3
Part1.3.2 Gibbs Sampler Unit Tests
'''

#Positive unit tests
Dna1 = ["CGCCCCTCTCGGGGGTGTTCAGTAAACGGCCA", "GGGCGAGGTATGTGTAAGTGCCAAGGTGCCAG",
        "TAGTACCGAGACCGAAAGAAGTATACAGGCGT", "TAGATCAAGTTTCAGGTGCACGTCGGTGAACC",
        "AATCCACCAGCTCCACGTGCAATGTTGGCCTA"]
k1 = 8
t1 = 5
N1 = 100
repeat1 = 20

Dna2 = ["AATTGGCACATCATTATCGATAACGATTCGCCGCATTGCC", "GGTTAACATCGAATAACTGACACCTGCTCTGGCACCGCTC",
        "AATTGGCGGCGGTATAGCCAGATAGTGCCAATAATTTCCT", "GGTTAATGGTGAAGTGTGGGTTATGGGGAAAGGCAGACTG",
        "AATTGGACGGCAACTACGGTTACAACGCAGCAAGAATATT", "GGTTAACTGTTGTTGCTAACACCGTTAAGCGACGGCAACT",
        "AATTGGCCAACGTAGGCGCGGCTTGGCATCTCGGTGTGTG", "GGTTAAAAGGCGCATCTTACTCTTTTCGCTTTCAAAAAAA"]
k2 = 6
t2 = 8
N2 = 100
repeat2 = 20

#Negative unit test
Dna3 = ["AAAAAA", "TTTTTT", "CCCCCC", "GGGGGG"]
k3 = 3
t3 = 4
N3 = 100
repeat3 = 20
