'''
CISC 471 HW3
Part1.2.2 Randomized Motif Search Unit Tests
'''

#Positive unit tests
Dna1 = ['CGCCCCTCTCGGGGGTGTTCAGTAAACGGCCA','GGGCGAGGTATGTGTAAGTGCCAAGGTGCCAG',
        'TAGTACCGAGACCGAAAGAAGTATACAGGCGT','TAGATCAAGTTTCAGGTGCACGTCGGTGAACC',
        'AATCCACCAGCTCCACGTGCAATGTTGGCCTA']
k1 = 8
t1 = 5

Dna2 = ["AATTGGCACATCATTATCGATAACGATTCGCCGCATTGCC", "GGTTAACATCGAATAACTGACACCTGCTCTGGCACCGCTC",
        "AATTGGCGGCGGTATAGCCAGATAGTGCCAATAATTTCCT", "GGTTAATGGTGAAGTGTGGGTTATGGGGAAAGGCAGACTG",
        "AATTGGACGGCAACTACGGTTACAACGCAGCAAGAATATT", "GGTTAACTGTTGTTGCTAACACCGTTAAGCGACGGCAACT",
        "AATTGGCCAACGTAGGCGCGGCTTGGCATCTCGGTGTGTG", "GGTTAAAAGGCGCATCTTACTCTTTTCGCTTTCAAAAAAA"]
k2 = 6
t2 = 8

#Negative unit test
Dna3 = ["AAAAAA", "TTTTTT", "CCCCCC", "GGGGGG"]
k3 = 3
t3 = 4
